site_name: Újvilág Birodalom Wiki
site_description: Vanilla-közeli, békés Minecraft szerver felnőtt közösséggel
site_url: https://FELHASZNALONEV.github.io/ujvilag-wiki/

theme:
  name: material
  language: hu
  palette:
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Világos mód
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Sötét mód
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
  logo: assets/logo.png
  favicon: assets/logo.png

nav:
  - Főoldal: index.md
  - Gyors indulás: gyors-indulas.md
  - Rangrendszer: rangok.md
  - Gazdasági rendszer: gazdasag.md
  - Határkövek: hatarkovek.md
  - Utazás: utazas.md
  - Ládaboltok és Piactér: piacter.md
  - Ősi Bűvölés: osi-mestersegek.md
  - Álmok-Ura: almok-ura.md
  - Szabályzat: szabalyzat.md
  - Parancsok: parancsok.md
  - Szerver infó: szerver-info.md
  - Közösségi tartalom:
      - kozossegi/index.md
  - Blog:
      - blog/index.md

plugins:
  - search:
      lang: hu
  - blog:
      blog_dir: blog
      post_date_format: yyyy. MMMM dd.
      archive_name: Archívum
      categories_name: Kategóriák
      pagination_per_page: 5

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-WGBNHTCZLW
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/MdBWZhAgCy
      name: Discord
